language: node_js
node_js: node
services: mongodb
deploy:
  api_key:
    secure: x15zgVTwENaWi15B25AH0kYi0rVqJgOZhC7jGUlSQnuXYIXheAkCb348izrPNklya6YmElpQilD/SnyVL3iGoMpllDyyWuz8uv334OaHecAKQ85KnKdLStnYvOwASRipSlRMVyHnaGRRYvOYrl6L5yqKPy6mjVNgFYoDBmrysca25Y7gFjFMJWqakDJw/ejwQzxqRCO/8hQJJTjBVWNCaUlPktUtL8USuAkT7n+p5oftp52adgCNbmcWHManUIh6A44htvZOOUvFV+iwdyXBk9vimx3xmVQVN6z0MdQwbVsM3mH4hgXDAuxr9iQ/Epa/EHFMdN4QufcHN3qHKjxJfA5xxFAUm6rjEKkmWWol7HT1tKNljgGJWyhmvEMTjc4Byp5fD3t3TeFSfMkrqkZSkSv3kWn55k15zzokFg03BVzgJO6ditpBZ1XRqdtZeiEI5d5jFEMGZqt8v5NL1jowEQw7RgzO3+OG9ckeG3O5+OX32G987rrFBtK8tIG+NGwv/A8YaRj4Fu7dWl3ak2YKsTlPN6EfNw6LDe8HQ/3KDkgFb8BQty8JCUvdwo/vN4EJaETY261QRJJSrB6Qw6qVt7bTEQkU8EkZeIOQ5fxuPGjSFj2hZPkiRNqluyRDYj0ydyxj5n5bgj3JFfl9N+jqCYE9EFf6Za5JeakW67DkgNU=
